# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: YewTree Hub
email: mathew.teague@yewtreeweb.co.uk
description: Just a cool Jekyll site by Kubix.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yewtreeweb.co.uk/" # the base hostname & protocol for your site, e.g. http://example.com
# parmalink: /:title
twitter_link: https://twitter.com/yewtreeweb
facebook_link: https://m.facebook.com/Yew-Tree-Web-146294038864167/
linkedin_link: https://www.linkedin.com/in/mathewteague
instagram_link: https://www.instagram.com/mat.teague/
github_link: https://github.com/YewTreeWeb
gitlab_link: https://gitlab.com/YewTreeWeb

# Pagination V2
pagination:
  enabled: true
  debug: false
  per_page: 15
  permalink: "/page/:num/"
  title: ":title - Page :num of :max"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
# Plugins
plugins:
  - jekyll-algolia
  - jekyll-feed
  - jekyll/figure
  - jekyll-paginate-v2
  - jekyll-picture-tag
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll-typogrify

# Include from processing.
include:
  - _pages
  - .htaccess

# Collections
collections:
  components: # Set a collection called pages that way the permalink will be by default url/page instead of url/pages/page.
    output: true
  helpers:
    output: true
  experiments:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package.json
  - bower.json
  - .bowerrc
  - yarn.lock
  - package-lock.json
  - .jekyll-assets-cache
  - .sass-cache/
  - Rakefile
  - README.md
  - gulpfile.js
  - gulpfile.babel.js
  - .babelrc.js
  - flightplan.js
  - markdown.style.rb
  - .mdlrc
  - .scss-lint.yml
  - .eslintignore
  - .eslintrc.js
  - .gitattributes
  - .gitignore
  - .editorconfig
  - .travis.yml
  - .codeclimate.yml
  - .github/
  - CHANGELOG.md
